# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, 2.17.0]

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Otherwise pageloader's PO files/mockito's mock files will cause the analyzer to panic
      - name: Run build_runner
        run: dart run build_runner build

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart run build_runner test -- -p chrome
