name: server_communication
description: Server Communication
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  http: ^0.13.3
  jsonpadding: ^1.0.2
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^1.7.0
  build_test: ^1.3.6
  build_web_compilers: ^2.4.0
